# Generated by Django 4.1.3 on 2022-11-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0002_show_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='showsearchfields',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
