# Generated by Django 4.1.3 on 2022-11-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0004_alter_show_slug_alter_showsearchfields_odour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showsearchfields',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
