# Generated by Django 4.1.3 on 2022-11-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0005_alter_showsearchfields_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='PersonalNotes',
            field=models.BooleanField(default=True, verbose_name=' _PersonalNotes'),
        ),
        migrations.AddField(
            model_name='showsearchfields',
            name='EnvironmentNotes',
            field=models.BooleanField(default=False, verbose_name=' _In UK'),
        ),
        migrations.AddField(
            model_name='showsearchfields',
            name='MonthFoundNotes',
            field=models.BooleanField(default=False, verbose_name=' _In UK'),
        ),
        migrations.AddField(
            model_name='showsearchfields',
            name='WhereFoundNotes',
            field=models.BooleanField(default=False, verbose_name=' _In UK'),
        ),
    ]
