# Generated by Django 4.1.3 on 2022-11-14 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0006_show_personalnotes_showsearchfields_environmentnotes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='PersonalNotes',
            new_name='ShowPersonalNotes',
        ),
    ]
