# Generated by Django 4.1.3 on 2022-11-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0008_remove_show_showpersonalnotes_show_showfunginotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='ShowFungiNotes2',
            field=models.BooleanField(default=True, verbose_name=' _Fungi Notes2'),
        ),
    ]
