# Generated by Django 4.1.3 on 2023-09-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0002_alter_fungicomments_comments_alter_similarfungi_sfid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fungicomments',
            name='Comments',
            field=models.CharField(blank=True, default='no comments', max_length=5000),
        ),
    ]
