# Generated by Django 4.1.3 on 2024-01-26 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0005_gills_gillsdata_alter_gills_gillspresent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gills',
            name='GillsData',
        ),
    ]
