# Generated by Django 4.1.3 on 2024-01-26 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0006_remove_gills_gillsdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gills',
            old_name='Arrangement',
            new_name='GillArrangement',
        ),
        migrations.RenameField(
            model_name='gills',
            old_name='Attachment',
            new_name='GillAttachment',
        ),
        migrations.RenameField(
            model_name='gills',
            old_name='BruiseColour',
            new_name='GillBruiseColour',
        ),
        migrations.RenameField(
            model_name='gills',
            old_name='Colour',
            new_name='GillColour',
        ),
        migrations.RenameField(
            model_name='gills',
            old_name='Comments',
            new_name='GillComments',
        ),
        migrations.RenameField(
            model_name='gills',
            old_name='CutColour',
            new_name='GillCutColour',
        ),
        migrations.RenameField(
            model_name='gills',
            old_name='Milk',
            new_name='GillMilk',
        ),
    ]
