# Generated by Django 4.1.3 on 2024-01-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0007_rename_arrangement_gills_gillarrangement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poresandtubes',
            name='PoresPresent',
            field=models.CharField(blank=True, choices=[('initial', ''), ('NoData', 'NoData'), ('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20, null=True),
        ),
    ]
