# Generated by Django 4.1.3 on 2024-01-31 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0008_alter_poresandtubes_porespresent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poresandtubes',
            old_name='Milk',
            new_name='PoreMilk',
        ),
    ]
